### ISSUE TITLE
In AnalyzeLocalFile project ignite.mp4 should be copied to the build folder

### ISSUE THREAD

**Issue by BrendanJiang** [johndeu/BUILD2018#7]

**Comment by johndeu** [comment]
Thanks @BrendanJiang !

**Comment by johndeu** [comment]
Actually, just re-tested again and it is working or me... Not sure I understand what you meant by copying it? Are you debugging in VS Code?   When i run the project in VS Code it works fine.

**Comment by johndeu** [comment]
Are you possibly on a Mac and not PC? that would be interesting to check out - as i have not fully tested all of these on Mac yet.

**Comment by BrendanJiang** [comment]
I was testing on PC and debugging in VS code. This is what I added in *.csproj file, as otherwise in debugging mode the code won't be able to find ignite.mp4 in bin\Debug\netcoreapp2.0:
  <ItemGroup>
    <Content Include="ignite.mp4">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

**Comment by BrendanJiang** [comment]
The full text was interpreted as html thus didn't show up correctly. Let me remove all the <>'s.
  ItemGroup
    Content Include="ignite.mp4"
      CopyToOutputDirectory PreserveNewest/CopyToOutputDirectory
    /Content
  /ItemGroup

**Comment by johndeu** [comment]
Strange. I don't see that issue when i just open the project and hit F5... not sure why you do...
I dont have the mp4 in my debug\netcoreapp2.0 folder either.

**Comment by johndeu** [comment]
I  just added the Content and Copy to the csproj anyways.  Not sure if it is needed or not. 
Thanks for the feedback! Keep it coming.

Sync repo and confirm for me.
